# Generated by Django 3.1.1 on 2020-09-30 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionaire', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(default=1, null=True)),
                ('log', models.TextField(default='')),
                ('questionaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionaire.questionaire')),
            ],
        ),
    ]
