# Generated by Django 3.1.2 on 2021-03-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20)),
                ('staff_name', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=30)),
                ('job_desc', models.TextField(blank=True, max_length=200, null=True)),
                ('staff_contact', models.TextField(max_length=200)),
                ('arrest_date', models.DateTimeField()),
                ('is_convict', models.BooleanField()),
                ('image', models.ImageField(default='job.jpg', upload_to='staff_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(max_length=20)),
                ('student_name', models.CharField(default='Gun', max_length=30)),
                ('student_number', models.IntegerField()),
                ('student_maintenance', models.BooleanField()),
                ('student_description', models.TextField(default='lorem ispum', max_length=500)),
                ('student_availability', models.TextField(max_length=1000)),
                ('image', models.ImageField(default='default.jpg', upload_to='student_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_name', models.CharField(default='vehicle', max_length=20)),
                ('vehicle_no', models.IntegerField()),
                ('vehicle_description', models.TextField(default='lorem ispum', max_length=500)),
                ('vehicle_availability', models.TextField(max_length=500)),
                ('vehicle_maintenance', models.BooleanField()),
                ('image', models.ImageField(default='default.jpg', upload_to='vehicles_pics')),
            ],
        ),
    ]
