# Generated by Django 3.1.2 on 2021-03-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='is_convict',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='student_type',
            new_name='student_class',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='vehicle_availability',
            new_name='teacher_availability',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='vehicle_type',
            new_name='teacher_class',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='vehicle_description',
            new_name='teacher_description',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='vehicle_maintenance',
            new_name='teacher_maintenance',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='vehicle_no',
            new_name='teacher_no',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='arrest_date',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='vehicle_name',
        ),
        migrations.AddField(
            model_name='teachers',
            name='teacher_name',
            field=models.CharField(default='teacher', max_length=20),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='teachers_pics'),
        ),
    ]
