# Generated by Django 3.1.2 on 2021-04-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20210320_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='students',
            name='student_availability',
        ),
        migrations.RemoveField(
            model_name='students',
            name='student_maintenance',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='teacher_availability',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='teacher_maintenance',
        ),
        migrations.AddField(
            model_name='staffs',
            name='covid_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffs',
            name='covid_checked_2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='covid_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='students',
            name='covid_checked_2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='covid_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teachers',
            name='covid_checked_2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
