# Generated by Django 3.1.1 on 2020-09-30 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('reference_id', models.PositiveIntegerField(null=True)),
                ('questionaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionaire.questionaire')),
            ],
            options={
                'unique_together': {('reference_id', 'questionaire')},
            },
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=200)),
                ('next', models.PositiveIntegerField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionaire.questions')),
                ('questionaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionaire.questionaire')),
            ],
        ),
    ]
