# Generated by Django 3.1.1 on 2020-09-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finder', models.CharField(max_length=50)),
                ('encText', models.TextField(blank=True, null=True)),
                ('keys', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
